#!/bin/sh
#
# Start wheel_legged_robot_tspi
#

DAEMON=/usr/bin/wheel_legged_robot_tspi
PIDFILE=/var/run/wheel_legged_robot_tspi.pid
LOGFILE=/var/log/wheel_legged_robot_tspi.log

case "$1" in
    start)
        printf "Starting wheel_legged_robot_tspi: "
        start-stop-daemon -S -b -m -p $PIDFILE \
            -x /bin/sh -- -c "exec $DAEMON > $LOGFILE 2>&1"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping wheel_legged_robot_tspi: "
        start-stop-daemon -K -p $PIDFILE -s TERM
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
